### ISSUE TITLE
Does not work with jQuery 3.3.1

### ISSUE THREAD

**Issue by nicowxdvd** [mmkjony/enllax.js#15]
<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	 crossorigin="anonymous"></script>

212 Uncaught TypeError: $(...).enllax is not a function
